<a href="https://colab.research.google.com/github/ShreyaaChauhan/Deep-Learning/blob/main/tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1><b>Goal</b> Prepration for TensorFlow Developer Certification Exam by Google 🎯</h1> 
<h5><b>Author</b> Shreya Chauhan</h5> 

#In this notebook we will cover some fundamental concepts of tensoeflow using tensorflow library

we are going to cover the following concepts
*   Introduction to tensors
*   Getting infroamtion from tensors
*   Manipulating tensors
*   Tensor's and numpy
*   using tf.functio(way to speed up normal python functions)
*   Using GPU with tensors
*   And some examples










##Introduction to tensors

In [1]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.8.0


### Creating tensors with **tf.constant**

In [2]:
from tensorflow.python.ops.gen_array_ops import matrix_diag_part_v2
value = 78
scalar = tf.constant(value, dtype=float)
print(scalar)
value = [1,2,3]
vector = tf.constant(value)
print(vector)
#Here we are basica;y creating a vector
value = [[1, 2],[ 3, 4],[ 5, 6]]
matrix = tf.constant(value)
print(matrix)
value=[[[[1,2,3]]],[[[7,8,9]]],[[[14,15,16]]]]
tensor= tf.constant(value)
print(tensor)

tf.Tensor(78.0, shape=(), dtype=float32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[[[ 1  2  3]]]


 [[[ 7  8  9]]]


 [[[14 15 16]]]], shape=(3, 1, 1, 3), dtype=int32)


Some important points to note:-

Correct way of defining tf.constant is 
```
tf.constant(
    value, dtype=None, shape=None, name='Const'
)
```
If you initialise a tf.constant without specifying dtype then it is **init32** by default

*   If the argument dtype is not specified, then the type is inferred from the type of value
*   If dtype is specified, the resulting tensor values are cast to the requested dtype
*   If shape is set, the value is reshaped to match. Scalars are expanded to fill the shape

For more info visit this link :- https://www.tensorflow.org/api_docs/python/tf/constant










Use ndim (#No of dimension) to check the dimension fo the tensor

In [3]:
print(scalar.ndim)
print(vector.ndim)
print(matrix.ndim)
print(tensor.ndim)

0
1
2
4


* Scalar: a number
* Vactor: list
* Matrix: a 2D array
* tensor: nD array 

### Creating tensors with **tf.Variable**

In [4]:
#Create the same variable as above with as it is clear form it's name these will be variable i.e we can modify them
changeable_tensor = tf.Variable([1,2])
unchangeable_tensor = tf.constant([3,4])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4], dtype=int32)>)

In [5]:
#what if we have to modifu the changeable_tensor tensor
changeable_tensor[0].assign(2)


<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([2, 2], dtype=int32)>

In [6]:
#woohoo!!! we have changed that successfully. Now Let's try to change uchangeable_tensor
uchangeable_tensor[0].assign(4)

NameError: ignored

In [8]:
#Ooops!! we got an error


🔑 **Note** We rarely have to decide if we have to use `tf.Variable` or `tf.constant` as tesorflow does this for us.

### Creating **random tensors**

In [9]:
random_1 = tf.random.Generator.from_seed(42) # we use seed to generate same random value 
random_1 = random_1.normal(shape=(3,3)) # normal here means normal distribution
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,3))


In [10]:
random_1, random_2

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026],
        [-1.2573844 , -0.23193763, -1.8107855 ],
        [ 0.09988727, -0.50998646, -0.7535805 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026],
        [-1.2573844 , -0.23193763, -1.8107855 ],
        [ 0.09988727, -0.50998646, -0.7535805 ]], dtype=float32)>)

In [11]:

#Check if `random_1` and `random_2` are equal
random_1==random_2

<tf.Tensor: shape=(3, 3), dtype=bool, numpy=
array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])>

### Shuffle the order of tensors in tensolflow

In [12]:
not_shuffled = tf.constant([1,2,3,4,5])
not_shuffled

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [13]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([5, 1, 2, 4, 3], dtype=int32)>

In [14]:
tf.random.set_seed(10) # you'll get same shuffled desk everytime you'll try to run iot
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 4, 2], dtype=int32)>

If you want to read more about seed please follow this link<br> https://www.tensorflow.org/api_docs/python/tf/random/set_seed


### Other ways to create a tensor

In [15]:
#create a tensor of all ones
tf.ones([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [16]:
#create a tensor of all zeros
tf.zeros([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

### Creating a tensor from numpy array
<br>
Normally, we use numpy for array manupulation and tenorflow for working with tensors
<br>

🔑 **Note** The difference between a NumPy array and a tensor is that the tensors are backed by the accelerator memory like GPU and they are immutable, unlike NumPy arrays.

In [17]:
np_array = np.arange(1,25)
print(np_array)
tf_array = tf.constant(np_array, shape=(2,3,4))
print(tf_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4), dtype=int64)


### Getting information from tensors 

We would like to extract/get folowing attributes from a tensor:
* Shape
* Size
* Rank
* Axis or dimension

In [18]:
tensor = tf.ones([1,2,3,4,5])
tensor

<tf.Tensor: shape=(1, 2, 3, 4, 5), dtype=float32, numpy=
array([[[[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]],


        [[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]]]], dtype=float32)>

In [19]:
tensor.shape, tensor.ndim,  tf.size(tensor), tensor.dtype

(TensorShape([1, 2, 3, 4, 5]),
 5,
 <tf.Tensor: shape=(), dtype=int32, numpy=120>,
 tf.float32)

### Indexing and expanding in tensorflow

indexing behaves the same just like it does in normal python array

In [20]:
vector = tf.constant([1,2,3,4,5,6])

In [21]:
# to print array within some limiits
print(vector[1:4])
#to print the last element
print(vector[-1])
#to print every element except last element
print(vector[:-1])
#everything goes just as it is in 1 dimensional array
print(tensor[1:2,1:2,1:2,1:2,1:2])

tf.Tensor([2 3 4], shape=(3,), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
tf.Tensor([], shape=(0, 1, 1, 1, 1), dtype=float32)


In [22]:
# expanding tensors
tensor = tf.constant([[1,2],[3,4]])
#to get the last element of every row
print(tensor[:,-1])
new_tensor = tensor[...,tf.newaxis]
print(new_tensor)

tf.Tensor([2 4], shape=(2,), dtype=int32)
tf.Tensor(
[[[1]
  [2]]

 [[3]
  [4]]], shape=(2, 2, 1), dtype=int32)


In [23]:
#alternative ways for tf.newaxis
tensor = tf.constant([[1,2],[3,4]])
print(tensor.shape)
print(tf.expand_dims(tensor, axis = -1).shape) # adds extra dimension in the last
print(tf.expand_dims(tensor, axis = 1).shape) # adds extra dimension in the middle
print(tf.expand_dims(tensor, axis = 0).shape) #adds extra dimension in the front

(2, 2)
(2, 2, 1)
(2, 1, 2)
(1, 2, 2)


### Manipulating tensors

**basic operations**

In [24]:
tensor = tf.constant([[1,2],[3,4]])
#broadcasting
print(tensor+10) # please note original tensor is still unchanged
print(tensor*10)
print(tensor-10)

tf.Tensor(
[[11 12]
 [13 14]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[10 20]
 [30 40]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[-9 -8]
 [-7 -6]], shape=(2, 2), dtype=int32)


In [25]:
#by using tensorlow's inbuild function as well
print(tf.math.multiply(tensor,10))
print(tf.math.subtract(tensor,10))
print(tf.math.add(tensor,10))

tf.Tensor(
[[10 20]
 [30 40]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[-9 -8]
 [-7 -6]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[11 12]
 [13 14]], shape=(2, 2), dtype=int32)


**Matrix Multiplication**<br>
You can perform matrix multiplication by using following:
* `tf.matmul()`
* `tf.tensordot()`
* `@`

In [26]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

🔑 **Note** In matrix multiplication the column of left matrix need to match the rows of the right matrix only then we can perform the operation

In [27]:
a = tf.constant([[1,2,3],[4,5,6]])
b = tf.constant([[4,5,6],[7,8,9]])

In [28]:
tf.matmul(a,b) # we will get error here 

InvalidArgumentError: ignored

In [29]:
#Here we have rehsape the matrix b to match matrix a
tf.matmul(a,tf.reshape(b, shape=(3,2)))


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 40,  46],
       [ 94, 109]], dtype=int32)>

In [30]:
tf.matmul(a,tf.transpose(b))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 32,  50],
       [ 77, 122]], dtype=int32)>

In [31]:
tensor = tf.constant([[1,2],[3,4]])
tf.tensordot(tensor,tensor,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [32]:
tf.tensordot(tensor,tensor,axes=0)

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int32, numpy=
array([[[[ 1,  2],
         [ 3,  4]],

        [[ 2,  4],
         [ 6,  8]]],


       [[[ 3,  6],
         [ 9, 12]],

        [[ 4,  8],
         [12, 16]]]], dtype=int32)>

### Change the datatype of the tensor

In [33]:
tensor = tf.constant([[1,2],[3,4]])
print(tensor.dtype)
new_tensor = tf.cast(tensor, dtype = tf.float16) 
print(new_tensor.dtype)

<dtype: 'int32'>
<dtype: 'float16'>
