<a href="https://colab.research.google.com/github/ShreyaaChauhan/Deep-Learning/blob/main/tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1><b>Goal</b> Prepration for TensorFlow Developer Certification Exam by Google 🎯</h1> 
<h5><b>Author</b> Shreya Chauhan</h5> 

#In this notebook we will cover some fundamental concepts of tensoeflow using tensorflow library

we are going to cover the following concepts
*   Introduction to tensors
*   Getting infroamtion from tensors
*   Manipulating tensors
*   Tensor's and numpy
*   using tf.functio(way to speed up normal python functions)
*   Using GPU with tensors
*   And some examples










##Introduction to tensors

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.8.0


### Creating tensors with **tf.constant**

In [ ]:
from tensorflow.python.ops.gen_array_ops import matrix_diag_part_v2
value = 78
scalar = tf.constant(value, dtype=float)
print(scalar)
value = [1,2,3]
vector = tf.constant(value)
print(vector)
#Here we are basica;y creating a vector
value = [[1, 2],[ 3, 4],[ 5, 6]]
matrix = tf.constant(value)
print(matrix)
value=[[[[1,2,3]]],[[[7,8,9]]],[[[14,15,16]]]]
tensor= tf.constant(value)
print(tensor)

tf.Tensor(78.0, shape=(), dtype=float32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[[[ 1  2  3]]]


 [[[ 7  8  9]]]


 [[[14 15 16]]]], shape=(3, 1, 1, 3), dtype=int32)


Some important points to note:-

Correct way of defining tf.constant is 
```
tf.constant(
    value, dtype=None, shape=None, name='Const'
)
```
If you initialise a tf.constant without specifying dtype then it is **init32** by default

*   If the argument dtype is not specified, then the type is inferred from the type of value
*   If dtype is specified, the resulting tensor values are cast to the requested dtype
*   If shape is set, the value is reshaped to match. Scalars are expanded to fill the shape

For more info visit this link :- https://www.tensorflow.org/api_docs/python/tf/constant










Use ndim (#No of dimension) to check the dimension fo the tensor

In [ ]:
print(scalar.ndim)
print(vector.ndim)
print(matrix.ndim)
print(tensor.ndim)

0
1
2
4


* Scalar: a number
* Vactor: list
* Matrix: a 2D array
* tensor: nD array 

### Creating tensors with **tf.Variable**

In [ ]:
#Create the same variable as above with as it is clear form it's name these will be variable i.e we can modify them
changeable_tensor = tf.Variable([1,2])
unchangeable_tensor = tf.constant([3,4])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4], dtype=int32)>)

In [ ]:
#what if we have to modifu the changeable_tensor tensor
changeable_tensor[0].assign(2)


<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([2, 2], dtype=int32)>

In [ ]:
#woohoo!!! we have changed that successfully. Now Let's try to change uchangeable_tensor
uchangeable_tensor[0].assign(4)

NameError: ignored

In [ ]:
#Ooops!! we got an error


🔑 **Note** We rarely have to decide if we have to use `tf.Variable` or `tf.constant` as tesorflow does this for us.

### Creating **random tensors**

In [ ]:
random_1 = tf.random.Generator.from_seed(42) # we use seed to generate same random value 
random_1 = random_1.normal(shape=(3,3)) # normal here means normal distribution
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,3))


In [ ]:
random_1, random_2

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026],
        [-1.2573844 , -0.23193763, -1.8107855 ],
        [ 0.09988727, -0.50998646, -0.7535805 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026],
        [-1.2573844 , -0.23193763, -1.8107855 ],
        [ 0.09988727, -0.50998646, -0.7535805 ]], dtype=float32)>)

In [ ]:
#Check if `random_1` and `random_2` are equal
random_1==random_2

<tf.Tensor: shape=(3, 3), dtype=bool, numpy=
array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])>

### Shuffle the order of tensors in tensolflow

In [ ]:
not_shuffled = tf.constant([1,2,3,4,5])
not_shuffled

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([3, 2, 5, 1, 4], dtype=int32)>

In [ ]:
tf.random.set_seed(10) # you'll get same shuffled desk everytime you'll try to run iot
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 4, 2], dtype=int32)>